version: "3.8"
services:
  todo-app:
    image: raedbash/todo-app
    container_name: todo-app
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - prod.env
    ports:
      - "8080:80"
